from environs import Env
import os

os.environ.clear()

env = Env()
env.read_env('settings/.env')
# print(env.path())
# admins=env('ADMIN_IDS')
# print('admins:', admins)
ADMIN_IDS: list[int] = list(map(int, env('ADMIN_IDS').split(',')))

BOT_TOKEN = env('BOT_TOKEN')

CHAT_TO_SEND_BOOKING =  env('CHAT_TO_SEND_BOOKING')

CHAT_BANKET_THREAD_ID=env('CHAT_BANKET_THREAD_ID')
CHAT_DANCE_THREAD_ID=env('CHAT_DANCE_THREAD_ID')
CHAT_BOWLING_THREAD_ID=env('CHAT_BOWLING_THREAD_ID')
CHAT_KARAOKE_THREAD_ID=env('CHAT_KARAOKE_THREAD_ID')
CHAT_RESTORAN_THREAD_ID=env('CHAT_RESTORAN_THREAD_ID')
CHAT_KARTING_THREAD_ID=env('CHAT_KARTING_THREAD_ID')

CHANNEL_ID=env('CHANNEL_ID')

# documents
BAR_CARD_ID=env('BAR_CARD_ID')
CHILD_MENU_ID=env('CHILD_MENU_ID')
OSNOVNOE_MENU_ID=env('OSNOVNOE_MENU_ID')


# images
KARTING_IMAGE_1=env('KARTING_IMAGE_1')
KARTING_IMAGE_2=env('KARTING_IMAGE_2')
KARTING_IMAGE_3=env('KARTING_IMAGE_3')
KARTING_IMAGE_4=env('KARTING_IMAGE_4')
FURSHET_MENU_IMAGE=env('FURSHET_MENU_IMAGE')

TEST_AFISHA1=env('TEST_AFISHA1')
TEST_AFISHA2=env('TEST_AFISHA2', None)

TEST_BISNESS_LAUNCH1=env('TEST_BISNESS_LAUNCH1')
TEST_BISNESS_LAUNCH2=env('TEST_BISNESS_LAUNCH2')